typography_spectrum: 0.8921307343989611
color:
  brandStrength: 0.49029005505144596
  lightness: 0.01852305978536606
  saturation: 0.8505665124394
  rhythmicContrast: 0.5193096736911684
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
layout_spectrum: 0.25850891857407987
author:
  name: Kevin
name: The Crocombe Site
navigation:
  - name: Favorite Site
    url: 'http://apple.com'
    type: external
  - name: Photos of Us
    id: bd828d0b-47d9-4538-928e-9bc36141d9fc
    type: content
title: The goings on of the Crocombes in Denver
description: 'Shealyn, Kevin, Kai'
